[project]
name = "orches-compute-optimal-tts-rtx5070ti"
version = "0.1.0"
requires-python = "==3.10.*"
dependencies = [
    "accelerate==1.7.0",
    "antlr4-python3-runtime==4.11.1",
    "deepspeed==0.16.9",
    "dm-env==1.6",
    "dm-tree==0.1.9",
    "fschat[model_worker,webui]==0.2.36",
    "jsonlines==4.0.0",
    "latex2sympy2",
    "loguru==0.7.3",
    "modelscope==1.26.0",
    "numpy==1.26.4",
    "pylatexenc==2.10",
    "ray[cgraph,default]==2.43.0",
    "regex==2024.11.6",
    "scipy==1.14.1",
    "setproctitle==1.3.6",
    "setuptools-scm==8.2.0",
    "timeout-decorator==0.5.0",
    "torch==2.7.0",
    "torchaudio==2.7.0",
    "torchvision==0.22.0",
    "transformers==4.52.4",
    "typing-extensions==4.13.2",
    "vllm==0.9.1",
    "word2number==1.1",
    "xformers==0.0.30",
]

[tool.uv]
package = false

[tool.uv.sources]
latex2sympy2 = { path = "../../../third_party/compute-optimal-tts/src/envs/MATH/latex2sympy", editable = true }
torch = { index = "pytorch-cu128" }
torchaudio = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }

[tool.uv.extra-build-dependencies]
latex2sympy2 = ["setuptools"]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
